# Generated by Django 3.2 on 2022-07-06 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil_cuit', models.CharField(blank=True, default='---', max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Capital Federal', 'Capital Federal'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('JujuY', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], max_length=50)),
                ('codigo_postal', models.CharField(blank=True, max_length=8, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('documento', models.CharField(max_length=20)),
                ('mensaje', models.TextField(default='')),
                ('email', models.EmailField(blank=True, default='---@gmail.com', max_length=128, null=True)),
                ('estado', models.CharField(choices=[('A CONFIRMAR', 'A CONFIRMAR'), ('NO ACREDITADO', 'NO ACREDITADO'), ('ACREDITADO', 'ACREDITADO'), ('FACTURADO', 'FACTURADO'), ('DESPACHADO', 'DESPACHADO')], default='A CONFIRMAR', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mas_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(default='', max_length=20)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('EN FABRICA', 'EN FABRICA'), ('A DOMICILIO', 'A DOMICILIO'), ('A COORDINAR', 'A COORDINAR')], default='EN FABRICA', max_length=15, null=True)),
                ('condicion_afip', models.CharField(blank=True, choices=[('IVA Responsable No Inscripto', 'IVA Responsable No Inscripto'), ('IVA Sujeto Exento', 'IVA Sujeto Exento'), ('Consumidor Final', 'Consumidor Final'), ('Responsable Monotributo', 'Responsable Monotributo'), ('Proveedor del Exterior', 'Proveedor del Exterior'), ('Cliente del Exterior', 'Cliente del Exterior'), ('IVA Liberado - Ley 19.640', 'IVA Liberado - Ley 19.640'), ('Monotributista Social', 'Monotributista Social'), ('IVA No Alcanzado', 'IVA No Alcanzado')], default='Consumidor Final', max_length=30, null=True)),
                ('razon_social', models.CharField(blank=True, default='---', max_length=128, null=True)),
                ('domicilio_comercial', models.CharField(blank=True, default='---', max_length=128, null=True)),
                ('nombre_apellido_recibe', models.CharField(blank=True, default='---', max_length=128, null=True)),
                ('documento_recibe', models.CharField(blank=True, default='---', max_length=20, null=True)),
                ('domicilio_recibe', models.CharField(blank=True, default='---', max_length=50, null=True)),
                ('localidad_recibe', models.CharField(blank=True, default='---', max_length=50, null=True)),
                ('provincia_recibe', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Capital Federal', 'Capital Federal'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('JujuY', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucumán', 'Tucumán')], default='Buenos Aires', max_length=50)),
                ('codigo_postal_recibe', models.CharField(blank=True, default='---', max_length=8, null=True)),
                ('telefono_recibe', models.CharField(blank=True, default='---', max_length=15, null=True)),
                ('envio_otro', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedido',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Peso en Kg')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cada_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='EnviarFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/%d')),
                ('mensaje', models.TextField(default='')),
                ('enviar', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Enviar Factura',
                'verbose_name_plural': 'Enviar Factura',
            },
        ),
    ]
