# Generated by Django 3.2 on 2022-07-06 09:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('---', '---'), ('Arquitectura', 'Arquitectura'), ('Artes Plasticas', 'Artes Plasticas'), ('Ciencias Ambientales', 'Ciencias Ambientales'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Ciencia Sociales y Política', 'Ciencia Sociales y Política'), ('Filosofía', 'Filosofía'), ('Gastronomia', 'Gastronomia'), ('Geografía', 'Geografía'), ('Historia', 'Historia'), ('Infantil', 'Infantil'), ('Juvenil', 'Juvenil'), ('Manualidades y artesanias', 'Manualidades y artesanias'), ('Mediciana y Salud', 'Mediciana y Salud'), ('Narrativa', 'Narrativa'), ('Negocios', 'Negocios'), ('Religión', 'Religión'), ('Terapias', 'Terapias')], default='---', max_length=50)),
                ('slug', models.CharField(choices=[('---', '---'), ('Arquitectura', 'arquitectura'), ('Artes Plasticas', 'artes_plasticas'), ('Ciencias Ambientales', 'ciencias_ambientales'), ('Ciencia Ficción', 'ciencia_ficcion'), ('Ciencia Sociales y Política', 'ciencia_sociales_y_politica'), ('Filosofía', 'filosofia'), ('Gastronomia', 'gastronomia'), ('Geografía', 'geografia'), ('Historia', 'historia'), ('Infantil', 'infantil'), ('Juvenil', 'juvenil'), ('Manualidades y Artesanias', 'manualidades_y_artesanias'), ('Mediciana y Salud', 'mediciana_y_salud'), ('Narrativa', 'narrativa'), ('Negocios', 'negocios'), ('Religión', 'religion'), ('Terapias', 'terapias')], default='---', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='linea/%Y/%m/%d')),
                ('orden', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)], default=1)),
            ],
            options={
                'verbose_name': 'CATEGORÍA',
                'verbose_name_plural': 'CATEGORÍA',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('composicion', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/%d')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuento', models.IntegerField(default=0)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuento_mayorista', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Retirado', 'Retirado')], default='Borrador', max_length=10)),
                ('peso', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Peso en Kg')),
                ('categoria', models.ManyToManyField(to='productos.Categoria', verbose_name='Línea')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('imagen', models.FileField(default='defecto/defecto.png', upload_to='imagen_producto/%Y/%m/%d')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
